### ISSUE TITLE
Flexible symbol discovery

### ISSUE THREAD

**Issue by nmokkenstorm** [VKCOM/nocolor#7]
**Is your feature request related to a problem? Please describe.**

> Deptrac matches names by regexps, NoColor needs PHPDoc tags

**Describe the solution you'd like**

![image](https://user-images.githubusercontent.com/33529698/123631585-3467d700-d817-11eb-8b6e-2e78001ad016.png)

**Describe alternatives you've considered**
N/A

**Additional context**
Again, mostly a loose thought, but having the option to mark classes by regex _and_ annotations would be nice. Using one over the other shouldn't really interfere, it's just the discovery process that needs to be decoupled. Again: open for discussion/collaboration on this if it's a feature that'd be appreciated.

**Comment by i582** [comment]
Hello. Thanks for the issue.

We thought about this, the problem is that the automatic classes mark will cause a lot 
of functions to have colors, and because of this, there can be a combinatorial explosion.

On small projects, this probably won't be so bad, but on larger projects, placing a large 
number of colors can make NoColor work very slow.

When we thought about how we would work with colors, we came to the conclusion that 
colors should be used carefully and strictly in small quantities (about 1% colored functions).

Plus, the automatic color addition is implicit and if there are colors both in PHPDoc and in the 
automatic addition config can lead to inconvenience for understanding where and what colors. 
> In part, this can probably be solved by adding to the plugin, so that it tracks this and can show 
colors, taking into account the config.

But using only the automatic addition config may not be enough for all cases, for example, 
for colors for slow or fast functions or functions that go to the database.

I will discuss this with the team, maybe we will try to implement it.

**Comment by nmokkenstorm** [comment]
> [...] we came to the conclusion that colors should be used carefully and strictly in small quantities (about 1% colored functions).

makes sense, thanks for the explanation!

> I will discuss this with the team, maybe we will try to implement it.

I'd love to be kept in the loop on this. If the conclusion is that you're interested in implementing it I'd love to have a stab at it, I've been itching to have an excuse to do some serious go work.

**Comment by i582** [comment]
> > [...] we came to the conclusion that colors should be used carefully and strictly in small quantities (about 1% colored functions).
> 
> makes sense, thanks for the explanation!
> 
> > I will discuss this with the team, maybe we will try to implement it.
> 
> I'd love to be kept in the loop on this. If the conclusion is that you're interested in implementing it I'd love to have a stab at it, I've been itching to have an excuse to do some serious go work.

Hello.

We have decided so far that we will not add automatic color addition for now.
If it is necessary for the future, we will think again.

In the meantime, this looks like a simplification of use, which we don't want, since 
the concept of colors must be used carefully and in a precise way so that each color 
is set strictly according to what you want.
Automatic color addition does not contribute to this.

**Comment by nmokkenstorm** [comment]
Sad to hear, but I get the reasoning, duly noted!

**Comment by i582** [comment]
> Sad to hear, but I get the reasoning, duly noted!

In any case, thanks for opening this issue, thanks to which we were able to come to a final solution.
